-- VITASHIELD AI SECURITY GATEWAY SCHEMA
-- Copy and paste this script directly into your Supabase SQL Editor and click "Run" to set up your tables!

-- -------------------------------------------------------------
-- 1. Create Autoencoder States Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.autoencoder_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weights1 JSONB NOT NULL,                 -- Input to hidden layer weights matrix (e.g. 4x2 array)
    weights2 JSONB NOT NULL,                 -- Hidden to output layer weights matrix (e.g. 2x4 array)
    bias1 JSONB NOT NULL,                    -- Hidden layer bias array (e.g. size 2)
    bias2 JSONB NOT NULL,                    -- Output layer bias array (e.g. size 4)
    trained_samples_count INTEGER DEFAULT 0,  -- Total sample iteration count
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for loading the latest neural state instantly
CREATE INDEX IF NOT EXISTS idx_autoencoder_states_id_desc ON public.autoencoder_states (id DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.autoencoder_states ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read/write access (matching API Key authorization layer)
CREATE POLICY "Enable read access for all users" ON public.autoencoder_states FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.autoencoder_states FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 2. Create Sessions Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('active', 'blocked', 'challenged')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on sessions" ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users on sessions" ON public.sessions FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 3. Create Telemetry Logs Table (Stores detailed kinetics & fingerprints)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
    risk_score INTEGER NOT NULL,
    device_fingerprint JSONB NOT NULL,      -- UserAgent, screen, timezone, WebDriver status
    behavior_metrics JSONB NOT NULL,        -- Mouse events counts, typing delays, scrolls
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast session query lookup
CREATE INDEX IF NOT EXISTS idx_telemetry_logs_session_id ON public.telemetry_logs (session_id);

ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on telemetry" ON public.telemetry_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users on telemetry" ON public.telemetry_logs FOR INSERT WITH CHECK (true);
