-- VITASHIELD AI SECURITY GATEWAY SCHEMA
-- Copy and paste this script directly into your Supabase SQL Editor and click "Run" to set up your tables!

-- -------------------------------------------------------------
-- 1. Create Autoencoder States Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.autoencoder_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weights1 JSONB NOT NULL,                 -- Input to hidden layer weights matrix (e.g. 4x2 array)
    weights2 JSONB NOT NULL,                 -- Hidden to output layer weights matrix (e.g. 2x4 array)
    bias1 JSONB NOT NULL,                    -- Hidden layer bias array (e.g. size 2)
    bias2 JSONB NOT NULL,                    -- Output layer bias array (e.g. size 4)
    trained_samples_count INTEGER DEFAULT 0,  -- Total sample iteration count
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for loading the latest neural state instantly
CREATE INDEX IF NOT EXISTS idx_autoencoder_states_id_desc ON public.autoencoder_states (id DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.autoencoder_states ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read/write access (matching API Key authorization layer)
CREATE POLICY "Enable read access for all users" ON public.autoencoder_states FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.autoencoder_states FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 2. Create Sessions Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('active', 'blocked', 'challenged')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on sessions" ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users on sessions" ON public.sessions FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 3. Create Telemetry Logs Table (Stores detailed kinetics & fingerprints)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
    risk_score INTEGER NOT NULL,
    device_fingerprint JSONB NOT NULL,      -- UserAgent, screen, timezone, WebDriver status
    behavior_metrics JSONB NOT NULL,        -- Mouse events counts, typing delays, scrolls
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast session query lookup
CREATE INDEX IF NOT EXISTS idx_telemetry_logs_session_id ON public.telemetry_logs (session_id);

ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on telemetry" ON public.telemetry_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users on telemetry" ON public.telemetry_logs FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 4. Create Crawled Threat Intelligence Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.crawled_threat_intel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    source_url TEXT UNIQUE NOT NULL,
    content_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_crawled_threat_intel_url ON public.crawled_threat_intel (source_url);

ALTER TABLE public.crawled_threat_intel ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on crawled intel" ON public.crawled_threat_intel FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users on crawled intel" ON public.crawled_threat_intel FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 5. Threat Intelligence Indicators Table
--    Stores live IOCs: C2 IPs, malware URLs, CVE IDs
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.threat_intel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,                           -- 'CISA KEV' | 'abuse.ch URLhaus' | 'Feodo Tracker'
    category TEXT NOT NULL,                         -- 'cve_exploited' | 'malware_url' | 'c2_botnet_ip'
    indicator TEXT NOT NULL,                        -- CVE ID, URL, or IP address
    description TEXT,
    severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_threat_intel_indicator_source ON public.threat_intel (indicator, source);
CREATE INDEX IF NOT EXISTS idx_threat_intel_category ON public.threat_intel (category);
CREATE INDEX IF NOT EXISTS idx_threat_intel_severity ON public.threat_intel (severity);

ALTER TABLE public.threat_intel ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all on threat_intel" ON public.threat_intel FOR SELECT USING (true);
CREATE POLICY "Enable insert for all on threat_intel" ON public.threat_intel FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 6. Threat Feed Statistics Table
--    Records counts of newly discovered threats per daily run
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.threat_feed_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cves INTEGER DEFAULT 0,
    malicious_urls INTEGER DEFAULT 0,
    c2_ips INTEGER DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.threat_feed_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all on threat_feed_stats" ON public.threat_feed_stats FOR SELECT USING (true);
CREATE POLICY "Enable insert for all on threat_feed_stats" ON public.threat_feed_stats FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 7. Threat Risk Config Table
--    Auto-updated risk multiplier based on global threat level
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.threat_risk_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_multiplier DECIMAL(4,3) DEFAULT 1.0,      -- e.g. 1.0 = normal, 1.5 = elevated global threat
    new_kev_count INTEGER DEFAULT 0,
    new_c2_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.threat_risk_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all on threat_risk_config" ON public.threat_risk_config FOR SELECT USING (true);
CREATE POLICY "Enable insert for all on threat_risk_config" ON public.threat_risk_config FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 8. Create Self-Learning Audit Table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.self_learn_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prev_trained_count INTEGER NOT NULL,
    new_trained_count INTEGER NOT NULL,
    bot_samples_trained INTEGER NOT NULL,
    human_samples_trained INTEGER NOT NULL,
    avg_bot_error DECIMAL(12,10) NOT NULL,
    avg_human_error DECIMAL(12,10) NOT NULL,
    health_action TEXT NOT NULL,
    health_reason TEXT NOT NULL,
    final_lr DECIMAL(6,5) NOT NULL,
    ran_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.self_learn_audit ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all on self_learn_audit" ON public.self_learn_audit FOR SELECT USING (true);
CREATE POLICY "Enable insert for all on self_learn_audit" ON public.self_learn_audit FOR INSERT WITH CHECK (true);

-- -------------------------------------------------------------
-- 9. Create Database-Level HTTP Cron Trigger (pg_net / pg_cron)
-- -------------------------------------------------------------
-- Copy and run the following in your Supabase SQL Editor to enable automatic daily crawls:
--
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- CREATE EXTENSION IF NOT EXISTS pg_net;
-- 
-- SELECT cron.schedule(
--     'daily_threat_crawl',
--     '0 0 * * *',
--     $$
--     SELECT net.http_post(
--         url:='https://vita-shield.vercel.app/api/cron/crawl',
--         headers:=jsonb_build_object(
--             'Content-Type', 'application/json',
--             'Authorization', 'Bearer YOUR_CRON_SECRET_KEY'
--         )
--     );
--     $$
-- );
